### ISSUE TITLE
FIlters.pm -> Filters.pm

### ISSUE THREAD

**Issue by eserte** [jjn1056/Template-Pure#1]
It's hardly to notice, but there's an uppercase "I" in the filename Filters.pm: https://metacpan.org/source/JJNAPIORK/Template-Pure-0.003/lib/Template/Pure
Causes test failures on OS with case sensitive file systems.

**Comment by jjn1056** [comment]
Oh no, I didn't notice until I published... damn OS X!  Well its fixed in 0.004 and I will just schedule for delete on those old broken ones.  Sad I didn't notice your comment until now.  I'm going to leave this open until I see its good on CPAN.  thanks! -jnap

**Comment by jjn1056** [comment]
Seems all good now, I'm going to delete those old versions to be on the safe side.
