### ISSUE TITLE
Pod error

### ISSUE THREAD

**Issue by khwilliamson** [jjn1056/Template-Pure#8]
At this line

https://metacpan.org/source/JJNAPIORK/Template-Pure-0.014/lib/Template/Pure.pm#L2442

an L<> is missing its closing ">"

**Comment by jjn1056** [comment]
oh man, my pod foo is not great.  I have a new release coming in a bit, some minor tweaks.  I'll get that in as well.

**Comment by khwilliamson** [comment]
On 05/04/2016 03:30 PM, John Napiorkowski wrote:
> oh man, my pod foo is not great. I have a new release coming in a bit,
> some minor tweaks. I'll get that in as well.

Thanks.  You might want to try out Pod::Checker that looks for pod 
issues like this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jjn1056/Template-Pure/issues/8#issuecomment-217009767>
>

Th

**Comment by jjn1056** [comment]
got it fixed in a recent version, thanks!
